import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  pt: {
    nav: {
      home: 'Início',
      about: 'Sobre',
      experience: 'Experiência',
      skills: 'Habilidades',
      projects: 'Projetos',
      certificates: 'Certificações',
      books: 'Livros',
      achievements: 'Conquistas',
      contact: 'Contato',
      contactBtn: 'Falar Comigo',
      langTitle: 'Mudar idioma',
      langAria: 'Alternar Idioma',
      brand: 'Vendramini Informática',
      brandGlitch: 'SISTEMA COM FALHA',
      menuAria: 'Abrir Menu',
      trajectory: 'Trajetória',
      status: 'Disponível',
      statusOnline: 'Disponível para novos projetos',
      utilities: 'Utilitários',
      theme: 'Tema',
      themeLight: 'Claro',
      themeDark: 'Escuro',
      themeAria: 'Alternar tema do header',
      openCli: 'Abrir Terminal CLI Interativo & Easter Eggs',
      preferences: 'Preferências',
      bsod: {
        fatal: '[ERRO FATAL]',
        title: 'OCORREU UMA FALHA CRÍTICA NO SISTEMA RICARDO.DEV',
        subtitle: 'O núcleo do portfólio sofreu uma sobrecarga de cliques no logo. Coletando dados do dump de memória...',
        progress: '[████████████████] 100% CONCLUÍDO',
        stopLabel: 'STOP_CODE:',
        stopValue: 'CLIQUE_EXCESSIVO_NO_LOGO',
        moduleLabel: 'MODULE:',
        moduleValue: 'Ricardo.DEV.exe (0x00000DEV)',
        statusLabel: 'STATUS:',
        statusValue: 'REBOOT_AUTOMATICO_INICIADO',
        joke: '😎 Brincadeira! O sistema está intacto.',
        jokeDesc: 'Achou que iria derrubar meu site clicando no logo? Sou dev, o sistema é auto-regenerativo.',
        restoring: 'Restaurando interface em alguns instantes...',
      },
    },
    hero: {
      badge: 'Engenheiro de Software & Líder Técnico',
      greeting: 'Olá, me chamo',
      title: 'Soluções Web de Alta Performance & Design Cyberpunk',
      description: 'Fundador da Vendramini Informática. Especialista em aplicações web escaláveis, arquitetura de sistemas, desenvolvimento com IA e infraestrutura.',
      ctaProjects: 'Ver Projetos',
      ctaContact: 'Entre em Contato',
      location: 'Piracicaba, SP — Brasil',
      access: 'Acessar Empresa',
      prefix: 'Eu transformo ideias em',
      gradient: 'experiências digitais.',
      learnStory: 'Conhecer minha história',
      stackLabel: 'Full Stack & Liderança',
      stackArchitecture: 'Arquitetura',
      stackServices: 'Serviços',
      stackInfrastructure: 'Infraestrutura',
      stackGovernance: 'Governança',
      scrollHint: 'Role para explorar',
    },
    about: {
      badge: 'Sobre',
      title: 'Minha trajetória, minha visão e o que me move',
      buildToWork: 'Construir para funcionar',
      buildToWorkDesc: 'Não basta parecer bonito. Gosto de criar soluções que sejam úteis, estáveis e fáceis de evoluir.',
      solveProblems: 'Resolver problemas reais',
      solveProblemsDesc: 'Tecnologia tem valor quando resolve um problema de verdade e facilita a vida de quem está do outro lado.',
      peopleFirst: 'Pessoas antes da tecnologia',
      peopleFirstDesc: 'Experiência, comunicação e colaboração são tão importantes quanto código e ferramentas.',
      alwaysEvolving: 'Sempre evoluindo',
      alwaysEvolvingDesc: 'Cada projeto é uma oportunidade de aprender algo novo, testar ideias e melhorar o que já existe.',
      quote: `"Não quero apenas escrever código. Quero construir coisas que façam sentido."`,
    },
    stats: {
      repos: 'Repositórios Criados',
      prodSystems: 'Sistemas em Produção',
      platforms: 'Plataformas & Sites Publicados',
      tools: 'Tecnologias no Ecossistema',
      years: 'Anos de Trajetória',
      activeComercial: 'Soluções Comerciais Ativas',
    },
    timeline: {
      badge: 'Evolução & Trajetória',
      title: 'A jornada através do ',
      accent: 'tempo.',
      subtitle: 'Marcos da evolução técnica e profissional de Ricardo Vendramini ao longo dos anos.',
      projectsLabel: 'Projetos Principais:',
      technologiesLabel: 'Tecnologias Utilizadas:',
      achievementsLabel: 'Conquistas',
    },
    skills: {
      badge: 'Conhecimentos & Ferramentas',
      title: 'Ecossistema ',
      accent: 'tecnológico.',
      subtitle: 'Passe o mouse sobre qualquer tecnologia para pausar o carrossel e visualizar os detalhes completos.',
      viewAll: 'Ver Todas as Tecnologias',
      detailsTitle: 'Detalhes da Tecnologia',
      relatedProjects: 'Projetos Relacionados:',
      noResultsTitle: 'Nenhuma tecnologia encontrada',
      noResultsDesc: 'Tente ajustar a busca ou a categoria selecionada.',
      showingOf: 'Exibindo',
      of: 'de',
      technologies: 'tecnologias',
      closeCatalog: 'Fechar Catálogo',
      all: 'Todas',
      categories: {
        all: 'Todas',
        core: 'Linguagens & Core',
        frameworks: 'Frameworks & CMS',
        ai: 'IA & Agentic Coding',
        backend: 'Backend & Cloud',
        tools: 'Ferramentas & Design',
        deploy: 'Redes, Deploy & Infra',
      },
    },
    projects: {
      badge: 'Portfólio de Soluções',
      title: 'Coisas que eu ',
      accent: 'construí.',
      subtitle: 'Passe o mouse sobre qualquer projeto para pausar o carrossel ou clique no botão abaixo para explorar a galeria completa.',
      viewAll: 'Ver Todos os Projetos',
      viewCase: 'Ver Case Completo',
      openProject: 'Abrir Projeto',
      allGallery: 'Galeria Completa de Soluções',
      allTitle: 'Todos os Projetos & ',
      allAccent: 'Aplicações',
      allSubtitle: 'Explore o ecossistema completo de sistemas em produção, portais institucionais e projetos open source.',
      searchPlaceholder: 'Pesquisar por nome, tecnologia ou palavra-chave...',
      clear: 'Limpar',
      noResults: 'Nenhum projeto encontrado',
      noResultsDesc: 'Tente ajustar a busca ou o filtro de categoria selecionado.',
      showingOf: 'Exibindo',
      of: 'de',
      projectsCount: 'projetos',
      closeGallery: 'Fechar Galeria',
      categories: {
        all: 'Todas',
        saas: 'Plataforma / SaaS',
        portal: 'Portal Institucional',
        openSource: 'Open Source',
        ecommerce: 'E-Commerce',
      },
    },
    certificates: {
      badge: 'Especializações & Qualificações',
      title: 'Certificações ',
      accent: '& Credenciais',
      subtitle: 'Formação continuada, diplomas e credenciais profissionais reconhecidas.',
      viewAll: 'Ver Todas as Certificações',
      zoom: 'Ampliar Certificado',
      view: 'Visualizar Certificado',
      openOriginal: 'Abrir em tamanho original',
      issuer: 'Emissor:',
      allGallery: 'Galeria Completa de Certificações',
      allTitle: 'Todas as Certificações & ',
      allAccent: 'Credenciais',
      allSubtitle: 'Qualificações profissionais validadas em engenharia de software, design de interfaces, redes e desenvolvimento pessoal.',
      searchPlaceholder: 'Pesquisar por título, tecnologia ou competência...',
      clear: 'Limpar',
      noResults: 'Nenhuma certificação encontrada para os filtros aplicados.',
      resetFilters: 'Resetar Filtros',
      categories: {
        all: 'Todas',
        web: 'Web Design / UI/UX',
        frontend: 'Front-End',
        networks: 'Redes & Segurança',
        soft: 'Soft Skills',
        data: 'Análise de Dados',
        ai: 'Inteligência Artificial',
      },
    },
    books: {
      badge: 'Literatura & Publicações',
      title: 'Além do ',
      accent: 'código.',
      subtitle: 'Escrever é outra forma de criar. Obras autorais publicadas por Ricardo Vendramini unem ficção científica, suspense psicológico e reflexão sobre a natureza humana.',
      interact3d: 'Passe o mouse para interagir 3D',
      published: 'Publicado',
      release: 'Lançamento:',
      synopsis: 'Sinopse Oficial:',
      readFull: 'Ler Sinopse Completa',
      buyAmazon: 'Comprar na Amazon',
      buyUiclap: 'Comprar na UICLAP',
      openDetailsAria: 'Abrir detalhes do livro',
      coverAria: 'Capa do livro',
    },
    experience: {
      badge: 'Atuação Profissional',
      title: 'Experiência que vai ',
      accent: 'além do código.',
      subtitle: 'Liderança, gestão de processos, visão de negócios e excelência na entrega de soluções.',
      highlightLabel: 'Principais Contribuições & Impacto:',
    },
    leadership: {
      badge: 'Gestão & Pessoas',
      title: 'Tecnologia é feita por ',
      accent: 'pessoas.',
      subtitle: 'Princípios fundamentais de liderança que garantem ambientes saudáveis, alinhamento técnico e alta produtividade.',
    },
    achievements: {
      badge: 'Marcos & Feitos',
      title: 'Coisas que construí ao ',
      accent: 'longo do caminho.',
      subtitle: 'Conquistas consolidadas através de projetos de impacto, liderança e aprendizado técnico.',
      impactLabel: 'Impacto Consolidado',
      galleryTitle: 'Galeria de Conquistas & Segredos',
      
      all: 'Todas',
      unlocked: 'Liberadas',
      locked: 'Bloqueadas',
      noneUnlocked: 'Nenhuma conquista liberada ainda',
      noneUnlockedHint: 'Explore as seções do site, clique em elementos e use o terminal para desbloquear os segredos! 🎮',
      allDone: 'Parabéns! Você fez 100%! 🌟',
      allDoneHint: 'Que tal fazer tudo de novo? Use {cmd} no terminal! 🎮',
      lockedTitle: 'Conquista Bloqueada',
      unlockedLabel: 'Desbloqueada',
      hidden: 'Oculta',
      hideHint: 'Ocultar dica',
      hintHidden: 'Dica oculta • Clique no olho para ver',
      revealHint: 'Revelar dica',
      viewHint: 'Ver Dica',
      footerAllDone: '🌟 Você fez 100%! Que tal fazer tudo de novo?',
      footerHint: '🎮 Clique no ícone do olho para revelar a dica de cada segredo bloqueado!',
      toastLabel: 'Conquista desbloqueada',
      meta: {
        titulo: { title: 'Gosta de clicar, não?', description: 'Clique repetidamente no título para forçar uma falha crítica no sistema.', hint: '🔍 Dica: Tenha raiva de logos...' },
        konami: { title: 'Vai cheatar é?', description: 'Digite a sequência secreta ↑ ↑ ↓ ↓ ← → ← → B A para ativar o modo místico.', hint: '🔍 Dica: Va na tela inicial do site e digite o famoso codigo das franquias de jogos...' },
        matrix: { title: 'Vermelho ou azul?', description: 'Digite "matrix" no terminal e veja a chuva de caracteres caindo.', hint: '🔍 Dica: Acesse o terminal e digite o nome de uma famosa franquia de ficção científica...', postUnlockHint: '💡 Que tal tentar no passado também?...' },
        navinha: { title: 'Proteja a terra', description: 'Inicie "navinha" e defenda o mundo de invasores geométricos.', hint: '🔍 Dica: Que tal dar um "play"?...' },
        root: { title: 'Quem deixou isso aí?', description: 'Obtenha as credenciais de root nos bastidores do terminal.', hint: '🔍 Dica: Dê uma olhada ao redor assim que entrar no terminal ou tente solicitar acesso de superusuário digitando "root"...' },
        tilt: { title: 'Terremoto', description: 'Execute o comando "tilt" no terminal e faça a estrutura inteira do site balançar.', hint: '🔍 Dica: Faça as coisas balançarem no terminal...' },
        breakout: { title: 'Botando pra quebrar', description: 'Ative o modo Breakout, destrua os blocos do site com a raquete e a bolinha.', hint: '🔍 Dica: Digite o nome do jogo clássico de quebrar tijolos...', postUnlockHint: '💡 Como sera que eram os jogos no passado?...' },
        starwars: { title: 'Que a Força Esteja Com Você', description: 'Ative o modo Star Wars Crawl e transforme o site na abertura da galáxia.', hint: '🔍 Dica: Digite o nome de uma famosa saga espacial no terminal ou no teclado...' },
        clean: { title: 'Mania de Limpeza', description: 'Execute o comando "clean" no terminal e deixe a tela totalmente limpa.', hint: '🔍 Dica: Que tal limpar o site?...' },
        polyglot: { title: 'Poliglota Digital', description: 'Alterne o idioma do site entre Português e Inglês.', hint: '🔍 Dica: Tente trocar a linguagem pelo terminal...' },
        timewalker: { title: 'Visitante do Passado', description: 'Você encontrou uma maneira de navegar pela Internet como ela costumava ser em 1999.', hint: '🔍 Dica: Apenas digite a franquia de livros do Ricardo Vendramini no terminal...', postUnlockHint: '💡 Guarde o segredo de viajar no tempo...' },
        tardis: { title: 'Caixa Azul', description: 'Digite "tardis" no terminal para abrir uma porta para outro universo.', hint: '🔍 Dica: Uma caixa azul que é maior por dentro...' },
        doctorwho: { title: 'Médico Quem?', description: 'Digite "doctor" no terminal e descubra a resposta clássica da cultura pop.', hint: '🔍 Dica: Procure por um médico...' },
        sacrificio: { title: 'Sacrifício', description: 'Desbloqueou todas as outras conquistas e depois usou "achievements reset" para sacrificar seu progresso.', hint: '🔍 Dica: Desbloqueie todas as outras conquistas primeiro...' },
      },
    },
    easterEgg: {
      continue: 'Continuar Explorando o Portfólio',
    },
    terminal: {
      badge: 'CLI Interativo & Arcade',
      titleTerm: 'Terminal',
      online: 'ONLINE',
      arcadeMode: 'RICARDO.DEV Arcade Mode - Space Invaders',
      points: 'PONTOS:',
      lives: 'VIDAS:',
      exit: 'SAIR (ESC)',
      moveLeft: 'Mover para Esquerda',
      moveRight: 'Mover para Direita',
      shoot: 'ATIRAR (ESPAÇO)',
      passwordPrompt: '🔐 senha:',
      prompt: 'ricardo@dev:~$',
      passwordPlaceholder: 'digite a senha...',
      helpPlaceholder: "digite 'help' para ver os comandos...",
      viewAchievements: 'Ver Galeria de Conquistas (Bloqueadas & Desbloqueadas)',
      helpHint: 'no terminal para ver todos os comandos 🎮',
      adminPanel: 'RICARDO.DEV — Painel Administrativo v4.2.0',
      closePanel: 'FECHAR PAINEL (ESC)',
      closePanelTitle: 'Fechar Painel',
      removePostIt: 'Tirar post-it',
      memoDev: '📌 MEMO // DEV',
      reminder: '⚠️ Lembrete: trocar credenciais padrão antes do deploy em produção!',
      pressRestartSpace: 'Pressione [ESPAÇO] para Reiniciar ou [ESC] para Sair',
      victory: 'VITÓRIA! ALIENS DESTRUÍDOS',
      pressPlayAgainSpace: 'Pressione [ESPAÇO] para Jogar Novamente',
      gameOver: 'GAME OVER',
      gameEnded: '> Jogo encerrado. Digite \'help\' para ver mais comandos.',
      finalScore: 'Pontuação Final:',
      cmdUnknown: "Comando não reconhecido: '{cmd}'. Digite 'help' para ver os comandos.",
      aboutResp: 'RICARDO VENDRAMINI: Desenvolvedor, Líder & Criador de Soluções Digitais com foco em produtos de alta performance.',
      skillsResp: 'SKILLS: React, TypeScript, Node.js, Next.js, Supabase, SQL, Linux, Git, Tailwind CSS, Liderança de Equipes.',
      projectsResp: 'PROJETOS: C4T4T4U Eletrônicos, Elite House Piracicaba, Vendramini Informática, Cigana Morgana, Rei das Roms, Festa Fácil.',
      booksResp: 'LIVROS: Código, Processos & Pessoas | Da Ideia à Produção',
      contactResp: 'CONTATO: contato@ricardovendramini.dev | LinkedIn & GitHub: Ricardo Vendramini',
      matrixRunning: '> Executando protocolo Matrix...',
      konamiActivated: '> 🎮 Código Konami ativado! Abrindo modo místico...',
      cleanActivated: '> 🧹 Modo Limpeza Total ativado! Ocultando todos os elementos do site...',
      restoreActivated: '> ✨ Restaurando a estrutura e todos os elementos do site...',
      tiltActivated: '> ⚡ ALERTA DE SISMO: Modo TILT ativado! Balançando toda a estrutura do site...',
      breakoutActivated: '> 🧱 Modo BREAKOUT ativado! Transformando o site no jogo de destruir blocos...',
      starwarsActivated: '> 🌌 Modo STAR WARS ativado! Que a Força esteja com você...',
      achievementsReset: '🔄 CONQUISTAS REINICIADAS!',
      achievementsResetDesc1: '> Todos os segredos e post-it foram resetados com sucesso.',
      achievementsResetDesc2: '> Explore novamente o site e o terminal para redescobrir os easter eggs! 🎮',
      achievementsGallery: '🏆 GALERIA DE CONQUISTAS:',
      achievementsGalleryDesc1: '> Para visualizar todas as conquistas e segredos (bloqueadas e desbloqueadas), use o botão "Ver Galeria de Conquistas" localizado abaixo deste terminal.',
      achievementsGalleryDesc2: '> Para reiniciar todo o progresso de conquistas, digite "reset".',
      rootAccess: '🔐 ACESSO RESTRITO — Painel Root Ricardo.DEV',
      authNeeded: '> Autenticação necessária.',
      rootPasswordPrompt: '> Digite a senha de root para continuar...',
      passOk: '[OK] Senha aceita. Autenticando...',
      loadingPanel: '> Carregando painel administrativo...',
      connectingServer: '[░░░░░░░░░░░░░░░] 0% - Conectando ao servidor...',
      loadingModules: '[████░░░░░░░░░░░] 28% - Carregando módulos...',
      checkingPerms: '[████████░░░░░░░] 55% - Verificando permissões...',
      initDashboard: '[████████████░░░] 82% - Inicializando dashboard...',
      ready100: '[███████████████] 100% - Pronto!',
      openingPanel: '> Abrindo painel admin...',
      wrongPassword: '❌ Senha incorreta. Acesso negado.',
      tryAgain: '> Tente novamente com o comando',
      trollMessage: 'Achou que tinha um painel admin de verdade? 😂',
      rickrolled: 'Você foi Rickrolled pelo Ricardo.DEV 🎤',
    },
    breakout: {
      title: 'ATARI BREAKOUT ',
      gameLabel: 'DESTRUIDOR DE SITE',
      instructions: 'Controle a raquete com as',
      arrows: 'setinhas (← →)',
      orMouse: 'ou o Mouse',
      restartSiteEsc: 'Aperte ESC para restaurar o site!',
      blocksLabel: 'Blocos do Site',
      points: 'Pontos',
      desactivateSound: 'Desativar Som',
      activateSound: 'Ativar Som',
      restartGame: 'Reiniciar Jogo',
      restoreSiteEsc: 'Restaurar Site (ESC)',
      pausedTitle: 'JOGO PAUSADO',
      pausedDesc: 'Pressione Espaço ou clique abaixo para continuar destruindo os elementos.',
      continueDestroying: 'Continuar Destruindo',
      gameOverTitle: 'FIM DE JOGO',
      gameOverDesc: 'A bolinha caiu! Você pode reiniciar ou restaurar o site.',
      totalScore: 'Pontuação Total',
      tryAgain: 'Tentar Novamente',
      restoreSite: 'Restaurar Site',
      victoryTitle: 'SITE TOTALMENTE DESTRUÍDO! 🎉',
      victoryDesc: 'Você desintegrou todos os elementos da tela!',
      restoreEntireSite: 'Restaurar Site Inteiro',
    },
    starwars: {
      soundOff: 'Desativar Áudio',
      soundOn: 'Ativar Áudio',
      restoreGalaxy: 'Restaurar Galáxia (ESC)',
      intro: 'Há muito tempo em um console, muito distante...',
      galacticTitle: 'PORTFÓLIO GALÁCTICO',
      episode: 'EPISÓDIO IV',
      crawlTitle: 'O CÓDIGO DA GALÁXIA',
      crawlP1: 'É um período de revolução digital. Desenvolvedores rebeldes travam uma batalha épica contra sistemas lentos, designs ultrapassados e a falta de inovação na web.',
      crawlP2: 'Do coração de Piracicaba, o engenheiro {name} ergueu a {company}, fundindo tecnologia de ponta, design cyberpunk e inteligência artificial para trazer ordem ao ecossistema digital.',
      jediSkills: 'AS HABILIDADES DOS JEDI:',
      iconicProjects: 'PROJETOS EMBLEMÁTICOS:',
      finalLine: 'QUE A FORÇA DO CÓDIGO ESTEJA COM VOCÊ!',
      forceButton: 'Restaurar a Galáxia (ESC)',
    },
    contact: {
      title: 'Vamos Construir Algo Incrível Juntos?',
      subtitle: 'Estou disponível para novos projetos, consultoria técnica, liderança de software e parcerias.',
      sendBtn: 'Enviar Mensagem',
      badge: 'Vamos Conectar',
      hTitle: 'Tem uma ',
      hAccent: 'ideia?',
      hSub: 'Talvez eu consiga transformá-la em realidade.',
      whatsapp: 'Vamos conversar no WhatsApp',
      copied: 'E-mail Copiado!',
      copyEmail: 'Copiar Endereço de E-mail',
      company: 'Empresa',
      emailLabel: 'E-mail',
    },
    footer: {
      company: 'Empresa',
      rights: 'Todos os direitos reservados.',
      mission: 'Minha missão é transformar ideias em soluções digitais de alta performance através de engenharia de software, inteligência artificial e design intuitivo, entregando valor real a cada projeto.',
      about: 'Sobre',
      experience: 'Experiência',
      skills: 'Habilidades',
      projects: 'Projetos',
      contact: 'Contato',
    },
    misc: {
      all: 'Todas',
      close: 'Fechar',
      clear: 'Limpar',
      showing: 'Exibindo',
      of: 'de',
      cancel: 'Fechar',
    },
    cleanBanner: {
      active: 'Modo Limpeza Total Ativo — O site foi limpo!',
      restore: 'Restaurar Site',
    },
    techlab: {
      badge: 'Laboratório de Arquitetura',
      title: 'Como as peças se ',
      accent: 'conectam.',
      subtitle: 'Representação interativa da infraestrutura técnica e ecossistema de dados.',
      activeConnection: 'Conexão Ativa • 100% Uptime',
      nodes: {
        core: { name: 'Linguagens & Core', desc: 'JavaScript, TypeScript, Python, HTML5, CSS3, SQL' },
        ui: { name: 'Frameworks & UI', desc: 'React, Vite, Tailwind, Shadcn/UI, Canvas API, PWA' },
        backend: { name: 'Backend & Dados', desc: 'Supabase, Node.js, PostgreSQL, REST API' },
        os: { name: 'Ferramentas & OS', desc: 'Linux, Git, VSCode, Pygame' },
        deploy: { name: 'Deploy & Infra', desc: 'Vercel, Hostinger, Git / GitHub' },
      },
    },
    seo: {
      defaultTitle: 'Ricardo Vendramini | Desenvolvedor Full Stack & Arquiteto de Sistemas em Piracicaba',
      defaultDescription: 'Portfólio de Ricardo Vendramini: Engenheiro de software, desenvolvedor full stack e arquiteto de sistemas em Piracicaba-SP. Soluções web escaláveis, aplicações em produção e liderança técnica.',
      title: {
        hero: 'Ricardo Vendramini | Desenvolvedor Full Stack & Arquiteto de Sistemas em Piracicaba',
        about: 'Sobre | Ricardo Vendramini — Engenheiro de Software & Líder Técnico',
        experience: 'Experiência & Trajetória | Ricardo Vendramini — Líder Técnico',
        skills: 'Habilidades & Tecnologias | Ricardo Vendramini — Full Stack Developer',
        projects: 'Projetos & Portfólio | Ricardo Vendramini — Soluções Web em Produção',
        certificates: 'Certificações | Ricardo Vendramini — Especializações & Credenciais',
        books: 'Livros Autorais | Ricardo Vendramini — Literatura & Publicações',
        contact: 'Contato | Ricardo Vendramini — Desenvolvedor em Piracicaba, SP',
      },
      description: {
        hero: 'Engenheiro de software, desenvolvedor full stack e arquiteto de sistemas em Piracicaba-SP. Soluções web escaláveis, aplicações em produção e liderança técnica.',
        about: 'Conheça a trajetória, visão e princípios de Ricardo Vendramini: engenharia de software, arquitetura de sistemas, resolução de problemas reais e desenvolvimento orientado a pessoas.',
        experience: 'Experiência profissional de Ricardo Vendramini: gestão de processos, liderança técnica, visão de negócios e excelência na entrega de soluções de tecnologia.',
        skills: 'Ecossistema tecnológico de Ricardo Vendramini: linguagens, frameworks, backend, cloud, ferramentas e infraestrutura para aplicações web escaláveis.',
        projects: 'Portfólio de sistemas em produção, plataformas SaaS, portais institucionais e projetos open source desenvolvidos por Ricardo Vendramini.',
        certificates: 'Certificações e credenciais de Ricardo Vendramini em engenharia de software, UI/UX, redes, segurança, IA e análise de dados.',
        books: 'Livros autorais de Ricardo Vendramini: ficção científica, suspense psicológico e reflexões sobre a natureza humana.',
        contact: 'Entre em contato com Ricardo Vendramini, desenvolvedor full stack em Piracicaba-SP, para novos projetos, parcerias e oportunidades.',
      },
      retro1999: {
        returnBtn: '[ ⏳ RETORNAR A 2026 ]',
        headline1999: 'Seja Bem-vindo à minha Homepage Pessoal na Web! 🌐✨',
        bio1999: 'Olá! Eu sou o Ricardo! 👋 Bem-vindo ao meu cantinho na Internet! Sou apaixonado por computadores e adoro programação, redes e tecnologia desde criança. Aqui você vai encontrar meus projetos de código, programas, certificados e coisas legais da Web. Não se esqueça de assinar o meu Guestbook antes de ir embora!',
        notice: {
          header: '⚠️ VENDRAMINI INFORMÁTICA — CONEXÃO DISCADA ATIVA',
          title: "YOU'VE GOT MAIL! ✉️",
          welcomePrefix: 'Bem-vindo à réplica retrô da',
          welcomeBold: 'Vendramini Informática (Web 1.0 — 1999)',
          sub: 'Conectado a 56kbps com som MIDI ativo!',
          enterBtn: '[ ENTRAR NO SITE ]',
        },
        footer: {
          connected: '🌐 Connected to Vendramini Informática (Web 1.0) • Dial-Up 56.0 Kbps • TCP/IP Protocol Active',
          session: 'Vendramini Informática Interactive Session.',
        },
        aim: {
          title: '🌸 ICQ 99b — Vendramini (UIN: #99404199)',
          chatTitle: '💬 Conversa Direta ICQ (UIN: #99404199)',
          placeholder: 'Enviar mensagem no ICQ...',
          sendBtn: '[ Enviar ICQ ]',
          welcomeMsg: 'Uh-oh! Alguém te enviou uma mensagem no ICQ 99b!',
          danteMsg: 'Oi! Adicione meu UIN (#19998800) na sua lista do ICQ!',
        },
        tabs: {
          web: 'Read / Início',
          projetos: 'Projetos',
          skills: 'Skills',
          certificados: 'Certificados',
          trajetoria: 'Trajetória',
          livros: 'Livros',
          contato: 'Mail / Contato',
          msdos: 'MS-DOS Prompt',
          mycomputer: 'Meu Computador',
          coollinks: 'Links Legais',
        },
      },
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      experience: 'Experience',
      skills: 'Skills',
      projects: 'Projects',
      certificates: 'Certifications',
      books: 'Books',
      achievements: 'Achievements',
      contact: 'Contact',
      contactBtn: 'Get in Touch',
      langTitle: 'Switch language',
      langAria: 'Switch Language',
      menu: 'Open Menu',
      brand: 'Vendramini',
      brandGlitch: 'SYSTEM MALFUNCTION',
      menuAria: 'Open Menu',
      trajectory: 'Journey',
      status: 'Available',
      statusOnline: 'Open to new projects',
      utilities: 'Utilities',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeAria: 'Toggle header theme',
      openCli: 'Open Interactive CLI Terminal & Easter Eggs',
      preferences: 'Preferences',
      bsod: {
        fatal: '[FATAL ERROR]',
        title: 'A CRITICAL FAILURE HAS OCCURRED ON RICARDO.DEV',
        subtitle: 'The portfolio kernel was overloaded by logo clicks. Collecting memory dump...',
        progress: '[████████████████] 100% COMPLETED',
        stopLabel: 'STOP_CODE:',
        stopValue: 'EXCESSIVE_LOGO_CLICKS',
        moduleLabel: 'MODULE:',
        moduleValue: 'Ricardo.DEV.exe (0x00000DEV)',
        statusLabel: 'STATUS:',
        statusValue: 'AUTO_REBOOT_STARTED',
        joke: '😎 Just kidding! The system is intact.',
        jokeDesc: 'Thought you could take down my site by clicking the logo? I\'m a dev — the system is self-healing.',
        restoring: 'Restoring interface in a moment...',
      },
    },
    hero: {
      badge: 'Software Engineer & Tech Lead',
      greeting: 'Hi, I\'m',
      title: 'High-Performance Web Solutions & Cyberpunk Design',
      description: 'Founder of Vendramini Informática. Specialized in scalable web applications, systems architecture, AI-driven development, and tech infrastructure.',
      ctaProjects: 'View Projects',
      ctaContact: 'Get in Touch',
      location: 'Piracicaba, SP — Brazil',
      access: 'Visit Company',
      prefix: 'I turn ideas into',
      gradient: 'digital experiences.',
      learnStory: 'Learn My Story',
      stackLabel: 'Full Stack & Leadership',
      stackArchitecture: 'Architecture',
      stackServices: 'Services',
      stackInfrastructure: 'Infrastructure',
      stackGovernance: 'Governance',
      scrollHint: 'Scroll to explore',
    },
    about: {
      badge: 'About Me',
      title: 'My journey, my vision, and what drives me',
      pillarsToWork: 'Build to Work',
      pillarsToWorkDesc: 'It\'s not enough to just look good. I craft solutions that are reliable, stable, and easy to scale.',
      solveProblems: 'Solve Real Problems',
      solveProblemsDesc: 'Technology brings true value when it solves genuine business pain and simplifies user workflows.',
      peopleFirst: 'People First',
      peopleFirstDesc: 'User experience, clear communication, and teamwork are just as crucial as clean code and tools.',
      alwaysEvolving: 'Always Evolving',
      alwaysEvolvingDesc: 'Every project is a chance to learn new paradigms, test ideas, and refine existing architectures.',
      quote: '"I don\'t just want to write code. I want to build things that matter."',
    },
    stats: {
      repos: 'Repositories Created',
      prodSystems: 'Production Systems',
      platforms: 'Published Platforms & Sites',
      tools: 'Tools in the Ecosystem',
      years: 'Years of Experience',
      commercialComercial: 'Active Commercial Solutions',
    },
    timeline: {
      badge: 'Evolution & Milestones',
      title: 'Journey through ',
      accent: 'time.',
      subtitle: 'Key milestones of technical and professional evolution over the years.',
      projects: 'Key Projects:',
      technologiesLabel: 'Technologies Used:',
      achievementsLabel: 'Achievements',
    },
    skills: {
      badge: 'Skills & Toolkit',
      title: 'Technical ',
      accent: 'ecosystem.',
      subtitle: 'Hover over any skill card to pause the carousel and see full details.',
      viewAll: 'View All Skills',
      detailsTitle: 'Technology Details',
      relatedProjects: 'Related Projects:',
      noResultsTitle: 'No technologies found',
      noResultsDesc: 'Try adjusting your search or the selected category.',
      showingOf: 'Showing',
      of: 'of',
      technologies: 'technologies',
      closeCatalog: 'Close Catalog',
      categories: {
        all: 'All',
        core: 'Languages & Core',
        frameworks: 'Frameworks & CMS',
        ai: 'AI & Agentic Coding',
        backend: 'Backend & Cloud',
        tools: 'Tools & Design',
        deploy: 'Networks, Deploy & Infra',
      },
    },
    projects: {
      badge: 'Solutions Portfolio',
      title: 'Things I have ',
      accent: 'built.',
      subtitle: 'Hover over project cards to pause the marquee or click below to explore the full gallery.',
      viewAll: 'View All Projects',
      viewCase: 'View Full Case Study',
      openProject: 'Open Project',
      allGallery: 'Full Solutions Gallery',
      allTitle: 'All Projects & ',
      allAccent: 'Apps',
      allSubtitle: 'Explore the full ecosystem of production systems, institutional portals, and open source projects.',
      searchPlaceholder: 'Search by name, technology, or keyword...',
      clear: 'Clear',
      noResults: 'No projects found',
      noResultsDesc: 'Try adjusting your search or the selected category filter.',
      showingOf: 'Showing',
      of: 'of',
      projectsCount: 'projects',
      closeGallery: 'Close Gallery',
      categories: {
        all: 'All',
        saas: 'Platform / SaaS',
        portal: 'Corporate Portal',
        openSource: 'Open Source',
        ecommerce: 'E-Commerce',
      },
    },
    certificates: {
      badge: 'Certifications & Credentials',
      title: 'Certifications ',
      accent: '& Credentials',
      subtitle: 'Continuous education, diplomas, and recognized professional certifications.',
      viewAll: 'View All Certifications',
      zoom: 'View Certificate',
      view: 'Watch Certificate',
      openOriginal: 'Open at full size',
      issuer: 'Issuer:',
      allGallery: 'Full Certifications Gallery',
      allTitle: 'All Certifications & ',
      allAccent: 'Credentials',
      allSubtitle: 'Professional qualifications validated across software engineering, interface design, networking, and personal development.',
      searchPlaceholder: 'Search by title, technology, or skill...',
      clear: 'Clear',
      noResults: 'No certifications found for the applied filters.',
      resetFilters: 'Reset Filters',
      categories: {
        all: 'All',
        web: 'Web Design / UI-UX',
        frontend: 'Front-End',
        networks: 'Networking & Security',
        soft: 'Soft Skills',
        data: 'Data Analysis',
        ai: 'Artificial Intelligence',
      },
    },
    books: {
      badge: 'Books & Publications',
      title: 'Beyond the ',
      accent: 'code.',
      subtitle: 'Writing is another form of creating. Author-published works mixing sci-fi, psychological suspense, and insight into human nature.',
      interact3d: 'Hover to interact in 3D',
      published: 'Published',
      release: 'Release: ',
      releaseLabel: 'Release:',
      synopsis: 'Official Synopsis:',
      readFull: 'Read Full Synopsis',
      buyAmazon: 'Buy on Amazon',
      buyUiclap: 'Buy on UICAP',
      openDetailsAria: 'Open book details for',
      coverAria: 'Cover of the book',
    },
    experience: {
      badge: 'Professional Experience',
      title: 'Experience beyond ',
      accent: 'code.',
      subtitle: 'Leadership, process management, business vision, and delivery excellence.',
      highlightLabel: 'Key Contributions & Impact:',
    },
    leadership: {
      badge: 'Leadership & People',
      title: 'Tech is built by ',
      accent: 'people.',
      subtitle: 'Core leadership principles ensuring healthy team cultures, technical alignment, and high productivity.',
    },
    achievements: {
      badge: 'Achievements & Impact',
      title: 'Built along ',
      accent: 'the journey.',
      subtitle: 'Milestones achieved through impactful projects, leadership, and technical mastery.',
      impactLabel: 'Consolidated Impact',
      galleryTitle: 'Achievements & Secret Gallery',
      
      all: 'All',
      unlocked: 'Unlocked',
      locked: 'Locked',
      noneUnlocked: 'No achievements unlocked yet',
      noneUnlockedHint: 'Explore the sections, click elements, and use the terminal to unlock the secrets! 🎮',
      allDone: 'Congrats! You did 100%! 🌟',
      allDoneHint: 'How about doing it all again? Use {cmd} in the terminal! 🎮',
      lockedTitle: 'Locked Achievement',
      unlockedLabel: 'Unlocked',
      hidden: 'Hidden',
      hideHint: 'Hide hint',
      hintHidden: 'Hidden hint • Click the eye to reveal',
      revealHint: 'Reveal hint',
      viewHint: 'View Hint',
      footerAllDone: '🌟 You did 100%! How about doing it all again?',
      footerHint: '🎮 Click the eye icon to reveal a hint for each locked secret!',
      toastLabel: 'Achievement unlocked',
      meta: {
        titulo: { title: 'Clickaholic', description: 'Click repeatedly on the title to force a critical system failure.', hint: '🔍 Tip: Get angry at logos...' },
        konami: { title: 'Cheating, are we?', description: 'Type the secret sequence ↑ ↑ ↓ ↓ ← → ← → B A to unlock the mystic mode.', hint: '🔍 Tip: Go to the homepage and type the famous video game franchise code...' },
        matrix: { title: 'Red or blue?', description: 'Type "matrix" in the terminal and watch the digital rain fall.', hint: '🔍 Tip: Open the terminal and type the name of a famous sci-fi franchise...', postUnlockHint: '💡 How about trying in the past too?...' },
        navinha: { title: 'Protect the Earth', description: 'Start "spaceship" and defend the world from geometric invaders.', hint: '🔍 Tip: How about a "play"?...' },
        root: { title: 'Who left this here?', description: 'Obtain root credentials inside the terminal', hint: '🔍 Tip: Take a look around as soon as you enter the terminal or try requesting superuser access by typing "root"...' },
        tilt: { title: 'Earthquake', description: 'Run "tilt" in the terminal and make the entire site structure shake.', hint: '🔍 Tip: Make things shake in the terminal...' },
        breakout: { title: 'Breaking It Down', description: 'Activate Breakout Mode and smash the site blocks with the paddle and ball.', hint: '🔍 Tip: Type the name of the famous brick-breaking game...', postUnlockHint: '💡 I wonder what games were like in the past?...' },
        starwars: { title: 'May the Force Be With You', description: 'Activate Star Wars Crawl Mode and transform the site into a galaxy opening.', hint: '🔍 Tip: Type the name of a famous space saga in the terminal or keyboard...' },
        clean: { title: 'Clean Freak', description: 'Run "clean" in the terminal and leave the screen completely empty.', hint: '🔍 Tip: How about cleaning the site?...' },
        polyglot: { title: 'Digital Polyglot', description: 'Switch the website language between Portuguese and English.', hint: '🔍 Tip: Try changing the language via the terminal...' },
        timewalker: { title: 'Visitor from the Past', description: 'You found a way to navigate the Internet as it used to be back in 1999.', hint: '🔍 Tip: Just type Ricardo Vendramini\'s book franchise in the terminal...', postUnlockHint: '💡 Keep the secret of time travel...' },
        tardis: { title: 'Blue Box', description: 'Type "tardis" in the terminal to open a door to another universe.', hint: '🔍 Tip: A blue box that is bigger on the inside...' },
        doctorwho: { title: "Doctor Who?", description: 'Type "doctor" in the terminal and get the classic pop culture answer.', hint: '🔍 Tip: Look for a doctor...' },
        sacrificio: { title: 'Sacrifice', description: 'Unlocked all other achievements and then used "achievements reset" to sacrifice your progress.', hint: '🔍 Tip: Unlock all other achievements first...' },
      },
    },
    easterEgg: {
      continue: 'Keep Exploring the Portfolio',
    },
    terminal: {
      badge: 'Interactive CLI & Arcade',
      titleTerm: 'Terminal',
      online: 'ONLINE',
      arcadeMode: 'RICARDO.DEV Arcade Mode - Space Invaders',
      points: 'SCORE:',
      lives: 'LIVES:',
      exit: 'EXIT (ESC)',
      moveLeft: 'Move Left',
      moveRight: 'Move Right',
      shoot: 'SHOOT (SPACE)',
      passwordPrompt: '🔐 password:',
      prompt: 'ricardo@dev:~$',
      passwordPlaceholder: 'enter the password...',
      helpPlaceholder: "type 'help' to see commands...",
      viewAchievements: 'View Achievements Gallery (Locked & Unlocked)',
      helpHint: 'in the terminal to see all commands 🎮',
      adminPanel: 'RICARDO.DEV — Admin Panel v4.2.0',
      closePanel: 'CLOSE PANEL (ESC)',
      closePanelTitle: 'Close Panel',
      removePostIt: 'Remove post-it',
      memoDev: '📌 MEMO // DEV',
      reminder: '⚠️ Reminder: change default credentials before going to production!',
      pressRestartSpace: 'Press [SPACE] to Restart or [ESC] to Exit',
      victory: 'VICTORY! ALIENS DESTROYED',
      pressPlayAgainSpace: 'Press [SPACE] to Play Again',
      gameOver: 'GAME OVER',
      gameEnded: '> Game ended. Type \'help\' to see more commands.',
      finalScore: 'Final Score:',
      cmdUnknown: "Unknown command: '{cmd}'. Type 'help' to see the commands.",
      aboutResp: 'RICARDO VENDRAMINI: Developer, Leader & Creator of Digital Solutions focused on high-performance products.',
      skillsResp: 'SKILLS: React, TypeScript, Node.js, Next.js, Supabase, SQL, Linux, Git, Tailwind CSS, Team Leadership.',
      projectsResp: 'PROJECTS: C4T4T4U Electronics, Elite House Piracicaba, Vendramini Informática, Cigana Morgana, Rei das Roms, Festa Fácil.',
      booksResp: 'BOOKS: Code, Processes & People | From Idea to Production',
      contactResp: 'CONTACT: contact@ricardovendramini.dev | LinkedIn & GitHub: Ricardo Vendramini',
      matrixRunning: '> Running Matrix protocol...',
      konamiActivated: '> 🎮 Konami Code activated! Opening mystic mode...',
      cleanActivated: '> 🧹 Total Clean mode activated! Hiding all site elements...',
      restoreActivated: '> ✨ Restoring the structure and all site elements...',
      tiltActivated: '> ⚡ EARTHQUAKE WARNING: TILT mode activated! Shaking the whole site...',
      breakoutActivated: '> 🧱 BREAKOUT mode activated! Turning the site into a brick breaker game...',
      starwarsActivated: '> 🌌 STAR WARS mode activated! May the Force be with you...',
      achievementsReset: '🔄 ACHIEVEMENTS RESET!',
      achievementsResetDesc1: '> All secrets, fly, and post-it have been successfully reset.',
      achievementsResetDesc2: '> Explore the site and terminal again to rediscover the easter eggs! 🎮',
      achievementsGallery: '🏆 ACHIEVEMENTS GALLERY:',
      achievementsGalleryDesc1: '> To view all achievements and secrets (locked and unlocked), use the "View Achievements Gallery" button located below this terminal.',
      achievementsGalleryDesc2: '> To reset all achievement progress, type "reset".',
      rootAccess: '🔐 RESTRICTED ACCESS — Ricardo.DEV Root Panel',
      authNeeded: '> Authentication required.',
      rootPasswordPrompt: '> Type the root password to continue...',
      passOk: '[OK] Password accepted. Authenticating...',
      loadingPanel: '> Loading admin panel...',
      connectingServer: '[░░░░░░░░░░░░░░░] 0% - Connecting to server...',
      loadingModules: '[████░░░░░░░░░░░] 28% - Loading modules...',
      checkingPerms: '[████████░░░░░░░] 55% - Checking permissions...',
      initDashboard: '[████████████░░░] 82% - Initializing dashboard...',
      ready100: '[███████████████] 100% - Ready!',
      openingPanel: '> Opening admin panel...',
      wrongPassword: '❌ Incorrect password. Access denied.',
      tryAgain: '> Try again with the command',
      trollMessage: 'Did you really think there was a real admin panel? 😂',
      rickrolled: 'You got Rickrolled by Ricardo.DEV 🎤',
    },
    breakout: {
      title: 'ATARI BREAKOUT ',
      gameLabel: 'SITE DESTROYER',
      instructions: 'Control the paddle with the',
      arrows: 'arrow keys (← →)',
      orMouse: 'or the Mouse',
      restartSiteEsc: 'Press ESC to restore the site!',
      blocksLabel: 'Site Blocks',
      points: 'Points',
      desactivateSound: 'Disable Sound',
      activateSound: 'Enable Sound',
      restartGame: 'Restart Game',
      restoreSiteEsc: 'Restore Site (ESC)',
      pausedTitle: 'GAME PAUSED',
      pausedDesc: 'Press Space or click below to keep destroying the elements.',
      continueDestroying: 'Keep Destroying',
      gameOverTitle: 'END OF GAME',
      gameOverDesc: 'The ball fell! You can restart or restore the site.',
      totalScore: 'Total Score',
      tryAgain: 'Try Again',
      restoreSite: 'Restore Site',
      victoryTitle: 'SITE COMPLETELY DESTROYED! 🎉',
      victoryDesc: 'You disintegrated all the elements on the screen!',
      restoreEntireSite: 'Restore Whole Site',
    },
    starwars: {
      soundOff: 'Disable Audio',
      soundOn: 'Enable Audio',
      restoreGalaxy: 'Restore Galaxy (ESC)',
      intro: 'A long time ago in a console, far far away...',
      galacticTitle: 'GALACTIC PORTFOLIO',
      episode: 'EPISODE IV',
      crawlTitle: 'THE CODE OF THE GALAXY',
      crawlP1: 'It is a period of digital revolution. Rebel developers wage an epic battle against slow systems, outdated designs, and the lack of innovation on the web.',
      crawlP2: 'From the heart of Piracicaba, the engineer {name} founded {company}, merging cutting-edge technology, cyberpunk design, and artificial intelligence to bring order to the digital ecosystem.',
      jediSkills: 'THE JEDI SKILLS:',
      iconicProjects: 'ICONIC PROJECTS:',
      finalLine: 'MAY THE FORCE OF CODE BE WITH YOU!',
      forceButton: 'Restore the Galaxy (ESC)',
    },
    contact: {
      title: 'Let\'s Build Something Amazing Together',
      subtitle: 'Available for new projects, challenges, or collaborations.',
      sendBtn: 'Send Message',
      badge: 'Let\'s Connect',
      hTitle: 'Have an ',
      hAccent: 'idea?',
      hSub: 'Maybe I can help turn it into reality.',
      whatsapp: 'Chat on WhatsApp',
      copied: 'Email Copied!',
      copyEmail: 'Copy Email Address',
      company: 'Company ↗',
      emailLabel: 'Email',
    },
    footer: {
      company: 'Company',
      rights: 'All rights reserved.',
      mission: 'My mission is to transform ideas into high-performance digital solutions through software engineering, artificial intelligence, and intuitive design, delivering real value in every project.',
      about: 'About',
      experience: 'Experience',
      skills: 'Skills',
      projects: 'Projects',
      contact: 'Contact',
    },
    misc: {
      all: 'All',
      close: 'Close',
      clear: 'Clear',
      showing: 'Showing',
      of: 'of',
      cancel: 'Close',
    },
    cleanBanner: {
      active: 'Total Clean Mode Active — The site has been cleaned!',
      restore: 'Restore Site',
    },
    techlab: {
      badge: 'Architecture Lab',
      title: 'How the pieces ',
      accent: 'connect.',
      subtitle: 'Interactive representation of the technical infrastructure and data ecosystem.',
      activeConnection: 'Active Connection • 100% Uptime',
      nodes: {
        core: { name: 'Languages & Core', desc: 'JavaScript, TypeScript, Python, HTML5, CSS3, SQL' },
        ui: { name: 'Frameworks & UI', desc: 'React, Vite, Tailwind, Shadcn/UI, Canvas API, PWA' },
        backend: { name: 'Backend & Data', desc: 'Supabase, Node.js, PostgreSQL, REST API' },
        os: { name: 'Tools & OS', desc: 'Linux, Git, VSCode, PyTorch' },
        deploy: { name: 'Deploy & Infra', desc: 'Vercel, Hostinger, Git / GitHub' },
      },
    },
    seo: {
      defaultTitle: 'Ricardo Vendramini | Full Stack Developer & Systems Architect in Piracicaba, Brazil',
      defaultDescription: 'Ricardo Vendramini portfolio: Software engineer, full stack developer and systems architect in Piracicaba-SP. Scalable web solutions, production applications and technical leadership.',
      title: {
        hero: 'Ricardo Vendramini | Full Stack Developer & Systems Architect in Piracicaba, Brazil',
        about: 'About | Ricardo Vendramini — Software Engineer & Technical Leader',
        experience: 'Experience & Journey | Ricardo Vendramini — Technical Leader',
        skills: 'Skills & Technologies | Ricardo Vendramini — Full Stack Developer',
        projects: 'Projects & Portfolio | Ricardo Vendramini — Production Web Solutions',
        certificates: 'Certifications | Ricardo Vendramini — Qualifications & Credentials',
        books: 'Author Books | Ricardo Vendramini — Literature & Publications',
        contact: 'Contact | Ricardo Vendramini — Developer in Piracicaba, SP',
      },
      description: {
        hero: 'Software engineer, full stack developer and systems architect in Piracicaba-SP. Scalable web solutions, production applications and technical leadership.',
        about: 'Discover Ricardo Vendramini\'s journey, vision and principles: software engineering, systems architecture, solving real problems and people-first development.',
        experience: 'Ricardo Vendramini\'s professional experience: process management, technical leadership, business vision and excellence in delivering technology solutions.',
        skills: 'Ricardo Vendramini\'s technology ecosystem: languages, frameworks, backend, cloud, tools and infrastructure for scalable web applications.',
        projects: 'Portfolio of production systems, SaaS platforms, institutional portals and open source projects built by Ricardo Vendramini.',
        certificates: 'Ricardo Vendramini\'s certifications and credentials in software engineering, UI/UX, networking, security, AI and data analysis.',
        books: 'Ricardo Vendramini\'s authored books: science fiction, psychological suspense and reflections on human nature.',
        contact: 'Contact Ricardo Vendramini, full stack developer in Piracicaba-SP, for new projects, partnerships and opportunities.',
      },
      retro1999: {
        returnBtn: '[ ⏳ RETURN TO 2026 ]',
        headline1999: 'Welcome to my Personal Homepage on the Web! 🌐✨',
        bio1999: 'Hi! I\'m Ricardo! 👋 Welcome to my personal homepage! I\'m a computer enthusiast and I love programming, the Internet, networks, and cool tech stuff. Check out my software projects, certifications, pictures and book collection. Don\'t forget to sign my Guestbook before you leave!',
        notice: {
          header: '⚠️ VENDRAMINI INFORMÁTICA — DIAL-UP CONNECTED',
          title: "YOU'VE GOT MAIL! ✉️",
          welcomePrefix: 'Welcome to the retro replica of',
          welcomeBold: 'Vendramini Informática (Web 1.0 — 1999)',
          sub: 'Connected at 56kbps with active MIDI sound!',
          enterBtn: '[ ENTER SITE ]',
        },
        footer: {
          connected: '🌐 Connected to Vendramini Informática (Web 1.0) • Dial-Up 56.0 Kbps • TCP/IP Protocol Active',
          session: 'Vendramini Informática Interactive Session.',
        },
        aim: {
          title: '💬 Vendramini Instant Messenger (VIM)',
          chatTitle: 'Direct Chat with Ricardo_Vendramini',
          placeholder: 'Send instant message...',
          sendBtn: '[ Send ]',
          welcomeMsg: 'Uh-oh! Welcome to my 1999 Instant Messenger!',
          danteMsg: 'Did you know you can navigate through time using code?',
        },
        tabs: {
          web: 'Read / Home',
          projetos: 'Projects',
          skills: 'Skills',
          certificados: 'Certifications',
          trajetoria: 'Career',
          livros: 'Books',
          contato: 'Mail / Contact',
          msdos: 'MS-DOS Prompt',
        },
      },
    },
  },
};


const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('ricardodev_lang') || 'pt';
    } catch {
      return 'pt';
    }
  });

  const changeLang = (nextLang) => {
    setLang(nextLang);
    try {
      localStorage.setItem('ricardodev_lang', nextLang);
    } catch {}
  };

  const toggleLang = () => {
    const nextLang = lang === 'pt' ? 'en' : 'pt';
    changeLang(nextLang);
  };

  const t = (path) => {
    const keys = path.split('.');
    let current = translations[lang] || translations.pt;
    let found = true;
    for (const key of keys) {
      if (current && current[key] !== undefined) {
        current = current[key];
      } else {
        found = false;
        break;
      }
    }
    if (found && typeof current === 'string') return current;

    // Fallback to PT
    let fallback = translations.pt;
    let fallbackFound = true;
    for (const key of keys) {
      if (fallback && fallback[key] !== undefined) {
        fallback = fallback[key];
      } else {
        fallbackFound = false;
        break;
      }
    }
    if (fallbackFound && typeof fallback === 'string') return fallback;

    return path;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, toggleLang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      lang: 'pt',
      setLang: () => {},
      toggleLang: () => {},
      t: (path) => path,
    };
  }
  return context;
}